### PR TITLE
GCI support

### PR DESCRIPTION
**Pull request by sup39**
I tried to add GCI support (https://github.com/BitPatty/gctGenerator/issues/128#issuecomment-1311381347) for NTSC-J 1.0. The GCI Loader code reads custom save file from memory card to RAM (817F0000-817FDFFF), and executes the loaded Gecko code in the RAM (at 817FB000).

## Installation Instructions
1. Download `GCI Loader` code as GCT/INI file. This file should be put in `/codes/` if playing on Wii, and should be added as ***the last code*** if playing on Dolphin.
2. Download all codes you want as GCI file. This file should be put in `/MCBACKUP/` and restore with GCMM if playing on Wii, and should be put in the GCI folder if playing on Dolphin. 

## TODO
- [ ] Ensure no side effect occurs
- [x] Port the code to other versions

### CODE REVIEW

**Comment by BitPatty** [comment]
Can we have it download both the GCI and the GCT when clicking "Download"? Would be easier for users

**Comment by sup39** [comment]
I was thinking that some people may want to use GCI on Dolphin, so we may need to provide an option to download INI+GCI besides GCT+GCI. One solution might be adding GCT+GCI, INI+GCI, TXT+GCI as download format. Or maybe we can add another checkbox or button for downloading the loader for selected format file + GCI file.

**Comment by BitPatty** [comment]
Oh yeah I didn't consider Dolphin..

I like both options, though the additional dropdown options would probably make more sense since that determines the target format/loader. What do you think?

**Comment by sup39** [comment]
## Changes
- GCI Loader is now hidden from code list and GCI+XXX are added as download format. Users can now select GCI+GCT, INI+GCT, TXT+GCT, or GCI (only) to download the files directly
- The generated GCI file size is changed from 0xE000 (7 blocks) to 0x4000 (2 blocks), and the mount location is changed from 817F0000 to 817FA800
- A Return code (from GCI to GCT) is added to replace the F0000000 in GCI file
- The Gecko codes in GCI file will only be loaded from memory card once. Once the codes are loaded, the loading process is skipped

**Comment by sup39** [comment]
The latest version of GCI Loader is tested on all versions and is also being used by several players, and there seems to be no side effect. Since adding this funtionality to the GCT Generateor site does not affect the existing usage, I think it would be great to add it at this point as an option for those who want to bypass the 5000 bytes limit. I can add an "(experminental)" notice if it is desired. What do you think?

**Comment by BitPatty** [comment]
I would add an experimental notice as you suggested and then you can merge/deploy it

**Comment by BitPatty** [comment]
@sup39 @QbeRoot can we merge this?

**Comment by BitPatty** [comment]
I'll fix the conflict since I caused it

**Comment by BitPatty** [comment]
Thanks @sup39 :)

**Pull request merged**
